- hosts: telegraf
  tasks:
  - name: 01-检测Agent是否安装 wget
    yum: name=wget state=latest
  - name: 02-正在联网下载Agent包到主机
    shell: sudo wget https://dl.influxdata.com/telegraf/releases/telegraf-1.6.3-1.x86_64.rpm
  - name: 03-安装Agent
    shell: sudo yum -y localinstall /root/telegraf-1.6.3-1.x86_64.rpm
  - name: 04-正在进行权限设定
    shell: chmod o+rw /var/run/docker.sock
  - name: 05-正在配置Agent监控
    copy: src=./etc/telegraf.conf dest=/etc/telegraf/
  - name: 06-正在修改配置文件监听IP
    shell: sed -i 's/:9273/{{ ansible_facts.ens192.ipv4.address }}:9273/' /etc/telegraf/
  - name: 07-使用SYSTEMD启动Agent
    service: name=telegraf state=started
  - name: 08-将Agent加入开机自启
    systemd: name=telegraf enabled=yes
  - name: 09-清理安装包
    shell: rm -rf  /root/telegraf-1.6.3-1.x86_64.rpm